--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{sitename}}
  namespace: {{sitename}}
  labels:
    app: {{sitename}}
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: {{sitename}}
  template: 
    metadata: 
      labels: 
        app: {{sitename}}
    spec: 
      initContainers:
        - name: init-sites-volume
          image: "drupal:8.6"
          command: ['/bin/bash', '-c']
          args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']
          volumeMounts:
            - name: vol-drupal
              mountPath: /data
      containers: 
        - name: drupal
          image: "drupal:8.6"
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
            requests:
              memory: "500Mi"
              cpu: "100m"
          volumeMounts: 
            - name: vol-drupal
              mountPath: /var/www/html/modules
              subPath: modules
            - name: vol-drupal
              mountPath: /var/www/html/profiles
              subPath: profiles
            - name: vol-drupal
              mountPath: /var/www/html/sites
              subPath: sites
            - name: vol-drupal
              mountPath: /var/www/html/themes
              subPath: themes
      volumes: 
        - name: vol-drupal
          persistentVolumeClaim: 
            claimName: {{sitename}}-filestore-claim
