--- 
apiVersion: v1
kind: Service
metadata: 
  name: {{sitename}}-service
  namespace: {{sitename}}
spec:
  type: LoadBalancer
  externalIPs: #To use only in Microk8s or Kubeadm env
  - 10.0.2.4
  selector:
    app: {{sitename}}
  ports: 
    - name: {{sitename}}
      port: 8083
      targetPort: 80
      protocol: TCP