--- 
apiVersion: v1
kind: Service
metadata: 
  name: drupal-service
  namespace: drupal
spec:
  type: LoadBalancer
  externalIPs: #To use only in Microk8s or Kubeadm env
  - 10.0.2.4
  selector:
    app: drupal
  ports: 
    - name: drupal
      port: 8083
      targetPort: 80
      protocol: TCP