---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-filestore
  namespace: drupal
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /storage/drupal-filestore
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-filestore
  namespace: drupal
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /storage/drupal-mysql-filestore
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: drupal-filestore-claim
  namespace: drupal
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassName: ""
  resources: 
    requests: 
      storage: 1Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: drupal-mysql-filestore-claim
  namespace: drupal
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassName: ""
  resources: 
    requests: 
      storage: 1Gi
