--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{sitename}}-mysql
  namespace: {{sitename}}
  labels:
    app: {{sitename}}-mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: {{sitename}}-mysql
  template: 
    metadata: 
      labels: 
        app: {{sitename}}-mysql
    spec: 
      initContainers:
        - name: init-db-volume
          image: "mysql:5.7.38"
          command: ['/bin/bash', '-c']
          args: ['touch /var/lib/mysql/readme.md;'] #Just to create the local folder
          volumeMounts:
            - name: vol-drupal-mysql
              mountPath: /var/lib/mysql
      containers: 
        - name: {{sitename}}-mysql
          image: "mysql:5.7.38"
          env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{sitename}}-mysql-secret
                key: password
          - name: MYSQL_DATABASE
            value: {{sitename}}-database
          ports:
          - containerPort: 3306
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
            requests:
              memory: "500Mi"
              cpu: "100m"          
          volumeMounts: 
            - name: vol-drupal-mysql
              mountPath: /var/lib/mysql
              subPath: dbdata
      volumes: 
        - name: vol-drupal-mysql
          persistentVolumeClaim: 
            claimName: {{sitename}}-mysql-filestore-claim
