---
apiVersion: v1
kind: Secret
metadata:
  name: {{sitename}}-mysql-secret
  namespace: {{sitename}}
type: kubernetes.io/basic-auth
stringData:
  password: {{password}}
  dbinstance: 127.0.0.1
  dbuser: {{sitename}}
